cloud:
  aws:
    credentials:
      access-key: AKIAQ3IRVK6RGOCB36D2
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false

application:
  bucket:
    name: tobiastestbucket/thumbnail


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090

